name: Release plugin

on:
  workflow_dispatch:

jobs:
  release-plugin:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: tobalan/plugin.video.jiotv
          path: plugin.video.jiotv
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          path: plugin.video.jiotv
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
      - name: chekout latest tag
        run: |
          git checkout ${{ steps.previoustag.outputs.tag }} -b main
      - name: Install zip
        uses: montudor/action-zip@v1
      - name: Zip output
        run: zip -qq -r plugin.video.jiotv-${{ steps.previoustag.outputs.tag }}.zip plugin.video.jiotv -x "plugin.video.jiotv/.github/*" "plugin.video.jiotv/.git/*"
      - uses: actions/checkout@v3
        with:
          path: repository
      - name: pull latest
        run: |
          git pull
          mv ../plugin.video.jiotv-2.3.1-1.zip Zips/plugin.video.jiotv
        # Commit all changed files back to the repository
          # cd ..
          # ls -lart
          # cd plugin.video.jiotv
          # ls -lart
      
        working-directory: repository
      - name: Commit updated plugin
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: repository
          commit_message: Automated plugin
